### ISSUE TITLE
bootstrap5 branch broken

### ISSUE THREAD

**Issue by petschki** [bluedynamics/yafowil.bootstrap#3]
`NameError: name 'tests_require' is not defined` when running buildout ... this was fixed lately in master ... can someone please merge this fix to `bootstrap5` branch?

/cc @rnixx

**Comment by rnixx** [comment]
The recent development branch is 2.0. since y.bootstrap supports several bootstrap versions now, y.plone probably needs to be adopted according to the README

**Comment by rnixx** [comment]
further, the recent dev branch of yafowil core package is 3.0

**Comment by petschki** [comment]
thanks! switching to 2.0 works for me
